### PR TITLE
Make "%property{key}" return an empty string instead of "null" when used in PatternJsonProvider

### LINKED ISSUE #765: PatternJsonProvider: omitEmptyFields doesn't work with %property(ENV_VAR)
### Discussed in https://github.com/logfellow/logstash-logback-encoder/discussions/760

<div type='discussions-op-text'>

<sup>Excerpt from original post by **ziomill** February 16, 2022</sup>
I'm trying to use the "**omitEmptyFields**" to print/omit an ENV variable, without success. If the ENV_VAR 'CONTAINER_NAMESPACE' is not populated, the logger prints "null" as the field's value rather than omit the field. 
...
This is my configuration:

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
    <providers>
        ...
        <pattern>
             <omitEmptyFields>true</omitEmptyFields>
             <pattern>
                 {"container-namespace":"%property{CONTAINER_NAMESPACE}"}
             </pattern>
        </pattern>
        ...
    </providers>
</encoder>
```

And this is the printed log record:

```js
{
   ...
   "container-namespace":"null"
   ...
}
```
</div>

### Root Cause

The Pattern json provider is using a standard Logback PatternLayout under the hood to resolve placeholders and converters in the pattern string. The resulting string is then converted into JSON and added to the final result. The "omitEmptyFields" property works by telling Jackson to omit fields whose value is considered empty.

When a property does not exist, the `%property{}` converter returns `null` and this value is unfortunately added "asis" to the internal StringBuilder. In this example, the original pattern is converted into the string `{"container-namespace":"null"}` before it is transformed into a valid JSON structure by Jackson. Since the property is not null but is assigned a String value, it is not filtered out by Jackson's "empty field" filtering mechanism.

### PR DESCRIPTION
**Pull request by brenuart**
The behaviour of the `%property{key}` conversion specifier is slightly modified to return an empty string when the property is not defined instead of `null` as it normally does. Assuming the "foo" property does not exist, the following configuration:

```xml
<pattern>
   { "foo": "%property{foo}" }
</pattern>
```

... will produce something like this:
```json
{ "foo": "" }
```

... instead of:
```json
{ "foo": "null" }
```

The `foo` property will now be successfully omitted when `omitEmptyField` is `true`.

The property conversion specifier now also accepts an optional default value to use when the property does not exist. Assuming the property "foo" is not defined, `%property{foo:-bar}` will return `bar` instead of an empty string.

People wanting to revert to the original behaviour of returning "null" instead of an empty string can explicitly defined a default value of `"null"`.

This should close #765

### CODE REVIEW

File: src/main/java/net/logstash/logback/pattern/EnhancedPropertyConverter.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+ * searched in the System environment.
+ * 
+ * 
+ * @author brenuart
+ */
+public class EnhancedPropertyConverter extends ClassicConverter {
+    /**
+     * Regex pattern used to extract the optional default value from the key name.
+     */
+    private static final Pattern PATTERN = Pattern.compile("(.+):-(.*)");
```
Comment (philsttr) [inline src/main/java/net/logstash/logback/pattern/EnhancedPropertyConverter.java:49]: might want to use `(.+?):-(.*)` here, to ensure the property name is before the first `:-`, in case `:-` appears later in the value.

File: src/main/java/net/logstash/logback/pattern/EnhancedPropertyConverter.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+import ch.qos.logback.classic.pattern.ClassicConverter;
+import ch.qos.logback.classic.pattern.PropertyConverter;
+import ch.qos.logback.classic.spi.ILoggingEvent;
+import ch.qos.logback.classic.spi.LoggerContextVO;
+
+/**
+ * Variation of the legacy Logback {@link PropertyConverter} with the option to specify a
```
Comment (philsttr) [inline src/main/java/net/logstash/logback/pattern/EnhancedPropertyConverter.java:28]: `legacy` seems a bit harsh, considering it is still used by logback.  I'd recommend removing the term legacy here

**Review by philsttr — COMMENTED** [review]
Looks good!  Just a couple super minor things.
